In [1]:
import json
import requests
import pandas as pd

In [2]:
#Creating an empty dataframe to store
alldata = pd.DataFrame()

resource_id = "f1765b54-a209-4718-8d38-a39237f502b3"  # This resource ID is for 2017 onwards. 
url = "https://data.gov.sg/api/action/datastore_search"
params = {'resource_id':resource_id, 'limit':10000}

#Initial query to obtain the total number
r = requests.get(url, params=params)
data = json.loads(r.content)
total = data['result']['total']

In [3]:
# Looping through the pages to get all the contents
# Looping is required since there is limit for each API call
pages = total//10000
for page in range(pages+1):
    offset = page*10000
    params = {'offset': offset, 'resource_id':resource_id, 'limit':10000}
    print("Retrieving approximately {} records out of {}.".format(offset,total))
    r = requests.get(url, params=params)
    data = json.loads(r.content)
    df = pd.DataFrame(data['result']['records'])
    alldata = pd.concat([alldata, df], axis=0)

Retrieving approximately 0 records out of 169584.
Retrieving approximately 10000 records out of 169584.
Retrieving approximately 20000 records out of 169584.
Retrieving approximately 30000 records out of 169584.
Retrieving approximately 40000 records out of 169584.
Retrieving approximately 50000 records out of 169584.
Retrieving approximately 60000 records out of 169584.
Retrieving approximately 70000 records out of 169584.
Retrieving approximately 80000 records out of 169584.
Retrieving approximately 90000 records out of 169584.

KeyboardInterrupt:

In [ ]:
alldata = alldata.drop_duplicates()
alldata.reset_index(inplace=True)

In [ ]:
alldata.to_json('data/data_source_2023.json', orient='records', lines=True)
print('Export to .json completed, ready for dataframe manipulation')

In [ ]:
RPI_dict = {'4Q2023': 180.2, '3Q2023': 178.5, '2Q2023': 176.2,'1Q2023': 173.6,'4Q2022': 171.9,'3Q2022': 168.1,'2Q2022': 163.9, '1Q2022': 159.5, 
'4Q2021': 155.7, '3Q2021': 150.6, '2Q2021': 146.4, '1Q2021': 142.2, '4Q2020': 138.1, '3Q2020': 133.9, '2Q2020': 131.9, 
'1Q2020': 131.5, '4Q2019': 131.5, '3Q2019': 130.9, '2Q2019': 130.8, '1Q2019': 131, '4Q2018': 131.4, '3Q2018': 131.6, 
'2Q2018': 131.7, '1Q2018': 131.6, '4Q2017': 132.6, '3Q2017': 132.8, '2Q2017': 133.7, '1Q2017': 133.9}

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame.from_dict(data=RPI_dict, orient='index').to_csv('RPI_dict.csv', header=False)

In [ ]:
RPI = pd.read_csv('data/RPI_dict.csv', header=None)
RPI_dict = dict(zip(RPI[0], RPI[1]))

## Using Geopy

In [ ]:
import numpy as np
import pandas as pd
from geopy import geocoders
from geopy.extra.rate_limiter import RateLimiter


# Rate-limit our requests since we're going to geocode
# many rows at once. Don't want to overwhelm the server-side!
agent = geocoders.Nominatim(user_agent = 'hdb_predictor')
_geocode = RateLimiter(agent.geocode, min_delay_seconds = 0.01)

# Prepare a fallback query that is more reliable/general than the initial query.
# country_codes limits our geocoding operation within Singapore (sg).
def geocode(query, fallback_query):
    try:
        result = _geocode(query, country_codes = ['sg'])
        if result is None:
            result = _geocode(fallback_query, country_codes = ['sg'])    
        return result
    except:
        print(f'Error obtaining data for {query}')

In [ ]:
df=pd.read_json('data/sample_pipe/data_source_100.json', lines=True)
df.head()

In [ ]:
df['address'] = df['block']+ " " + df['street_name']
df.head()

In [ ]:
unique_locations = df[['town', 'address']].drop_duplicates().reset_index(drop = True)

geocoding_queries = {}

for i in range(len(unique_locations)):
    address = unique_locations.loc[i, 'address']
    town = unique_locations.loc[i, 'town']
    geocoding_queries[address] = town

In [ ]:
geocoding_queries

In [ ]:
from tqdm import tqdm
geocoding_results = {}
for street_name, town in tqdm(geocoding_queries.items()):
    geocoding_results[street_name] = geocode(street_name, town)

In [ ]:
geocoding_results

In [ ]:
def postal_from_address(output):
    str = output.address
    postal_code = int(str.split(',')[-2].split(" ")[-1])
    return postal_code

In [ ]:
# Fill the dataset with latitude and longitude information from the
# geocoding results
df['latitude'] = df['address'].apply(lambda x: geocoding_results[x].latitude)
df['longitude'] = df['address'].apply(lambda x: geocoding_results[x].longitude)
df['postal'] = df['address'].apply(lambda x: postal_from_address(geocoding_results[x]))

# Make sure that the geocoding results are not grossly wrong
print(min(df['latitude']), "|", min(df['longitude']))
print(max(df['latitude']), "|", max(df['longitude']))

In [ ]:
df.head()

 ## Create a Module to 
 1. If the address exists in the existing list, use existing values.
 2. If the address does not exist, use Geopy and merge in.

In [4]:
# Create a unique dataframe for each address
df_full = pd.read_json('data/full_pipe/data_features.json', lines=True)
unique_location_full = df_full[['Location', 'distance_mrt', 'Postal']].drop_duplicates().reset_index(drop = True)
unique_location_full_test = unique_location_full[unique_location_full['Location']!='406 ANG MO KIO AVE 10']  # Removing one row to test the API
unique_location_full_test

                   Location  distance_mrt  Postal
0     546 ANG MO KIO AVE 10      0.926855  560546
1      330 ANG MO KIO AVE 1      0.845456  560330
2          425 BEDOK NTH RD      0.874538  460425
3       550 BEDOK NTH AVE 1      0.760373  460550
4      254 ANG MO KIO AVE 4      0.251354  560254
...                     ...           ...     ...
9480    676A YISHUN RING RD      1.236360  761676
9481      462A YISHUN AVE 6      1.694202  761462
9482       769 YISHUN AVE 3      0.570875  760769
9483      673C YISHUN AVE 4      1.103894  763673
9484      674B YISHUN AVE 4      1.199608  762674

[9484 rows x 3 columns]

In [5]:
df_query = pd.read_json('data/test_pipe/data_source.json', lines=True)
df_query['Location'] = df_query['block']+ " " + df_query['street_name']
df_query

,index,_id,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price,Location
0,0,1,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0,406 ANG MO KIO AVE 10
1,1,2,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0,108 ANG MO KIO AVE 4
2,2,3,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0,602 ANG MO KIO AVE 5
3,3,4,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0,465 ANG MO KIO AVE 10
4,4,5,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0,601 ANG MO KIO AVE 5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,9995,19996,2017-12,SEMBAWANG,5 ROOM,330,SEMBAWANG CL,13 TO 15,120.0,Improved,1999,80 years 07 months,428888.0,330 SEMBAWANG CL
19996,9996,19997,2017-12,SEMBAWANG,5 ROOM,333,SEMBAWANG CL,01 TO 03,120.0,Improved,1999,80 years 07 months,410000.0,333 SEMBAWANG CL
19997,9997,19998,2017-12,SEMBAWANG,5 ROOM,466B,SEMBAWANG DR,13 TO 15,110.0,Premium Apartment,2006,87 years 02 months,405000.0,466B SEMBAWANG DR
19998,9998,19999,2017-12,SEMBAWANG,5 ROOM,481,SEMBAWANG DR,04 TO 06,110.0,Improved,2000,81 years 08 months,375000.0,481 SEMBAWANG DR
19999,9999,20000,2017-12,SEMBAWANG,5 ROOM,317,SEMBAWANG VISTA,04 TO 06,121.0,Improved,1999,80 years 03 months,439000.0,317 SEMBAWANG VISTA

In [6]:
df_combined = pd.merge(df_query, unique_location_full_test, on='Location', how='left')
df_remaining = df_combined[df_combined['distance_mrt'].isna()].copy()
df_combined = df_combined[~df_combined['distance_mrt'].isna()].copy()
print('Number of non-unique rows to be queried via Geopy API for location:', df_remaining.shape[0])
print('Number of non-unique rows with location information ready:', df_combined.shape[0])

Number of non-unique rows to be queried via Geopy API for location: 2
Number of non-unique rows with location information ready: 19998

In [7]:
import numpy as np
import pandas as pd
from geopy import geocoders
from geopy.extra.rate_limiter import RateLimiter
from tqdm import tqdm

# Rate-limit our requests since we're going to geocode
# many rows at once. Don't want to overwhelm the server-side!
agent = geocoders.Nominatim(user_agent = 'hdb_predictor')
_geocode = RateLimiter(agent.geocode, min_delay_seconds = 0.01)

# Prepare a fallback query that is more reliable/general than the initial query.
# country_codes limits our geocoding operation within Singapore (sg).
def geocode(query, fallback_query):
    try:
        result = _geocode(query, country_codes = ['sg'])
        if result is None:
            result = _geocode(fallback_query, country_codes = ['sg'])    
        return result
    except:
        print(f'Error obtaining data for {query}')

def postal_from_address(output):
    str = output.address
    postal_code = int(str.split(',')[-2].split(" ")[-1])
    return postal_code

unique_locations = df_remaining[['town', 'Location']].drop_duplicates().reset_index(drop = True)
geocoding_queries = {}

for i in range(len(unique_locations)):
    address = unique_locations.loc[i, 'Location']
    town = unique_locations.loc[i, 'town']
    geocoding_queries[address] = town


geocoding_results = {}
for street_name, town in tqdm(geocoding_queries.items()):
    geocoding_results[street_name] = geocode(street_name, town)

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.18it/s]

In [8]:
###This is to create MRT names and MRT locations
import json
from src.misc_fn import nearest_mrt, numerical
mrt_name = []
mrt_loc = []
with open('data/mrt_list.json', 'r') as file:
    for line in file:
        item = json.loads(line)
        mrt_name.append(item['MRT'])
        loc = tuple([float(i) for i in item['location']])
        mrt_loc.append(loc)

mrt_results = {}
for street_name, town in geocoding_queries.items():
    mrt_results[street_name] = nearest_mrt(geocoding_results[street_name].latitude, geocoding_results[street_name].longitude, mrt_name, mrt_loc)

# Fill the dataset with latitude and longitude information from the
# geocoding results
df_remaining['Postal'] = df_remaining['Location'].apply(lambda x: postal_from_address(geocoding_results[x]))
df_remaining['distance_mrt'] = df_remaining['Location'].apply(lambda x: mrt_results[x])
print("Successfully calculated MRT distances")

Successfully calculated MRT distances

## Data Formatting and Output

In [9]:
df_combined_new = pd.concat([df_combined, df_remaining], axis=0).reset_index(drop=True)
df_combined_new

,index,_id,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price,Location,distance_mrt,Postal
0,1,2,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0,108 ANG MO KIO AVE 4,0.189980,560108
1,2,3,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0,602 ANG MO KIO AVE 5,0.532155,560602
2,3,4,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0,465 ANG MO KIO AVE 10,0.945372,560465
3,4,5,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0,601 ANG MO KIO AVE 5,0.498418,560601
4,5,6,2017-01,ANG MO KIO,3 ROOM,150,ANG MO KIO AVE 5,01 TO 03,68.0,New Generation,1981,63 years,275000.0,150 ANG MO KIO AVE 5,0.636985,560150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,9997,19998,2017-12,SEMBAWANG,5 ROOM,466B,SEMBAWANG DR,13 TO 15,110.0,Premium Apartment,2006,87 years 02 months,405000.0,466B SEMBAWANG DR,1.005889,752466
19996,9998,19999,2017-12,SEMBAWANG,5 ROOM,481,SEMBAWANG DR,04 TO 06,110.0,Improved,2000,81 years 08 months,375000.0,481 SEMBAWANG DR,0.701496,750481
19997,9999,20000,2017-12,SEMBAWANG,5 ROOM,317,SEMBAWANG VISTA,04 TO 06,121.0,Improved,1999,80 years 03 months,439000.0,317 SEMBAWANG VISTA,0.346359,750317
19998,0,1,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0,406 ANG MO KIO AVE 10,0.816971,560539
19999,6013,6014,2017-05,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 01 month,235000.0,406 ANG MO KIO AVE 10,0.816971,560539

In [12]:
data_list = []
for index, item in df_combined_new.iterrows():
    town_num, flat_num, area, age, transaction, storey, resale_price_adj = numerical(item)
    labelled_data = {
            'distance_mrt': item['distance_mrt'],
            'town': town_num,
            'area': area,
            'flat_num': flat_num,
            'age_transation': age,
            'lease_commence': item['lease_commence_date'],
            'transaction_yr': transaction,
            'transaction': item['month'],
            'storey_height': storey,
            'resale_price': item['resale_price'],
            'resale_price_adj': resale_price_adj,
            #find age at translation
            # 'resale_info': item,
            'Postal': item['Postal'],
            'Location': item['Location']
        }
    data_list.append(labelled_data)

#Write to a file eventually
count = 0
dst = open('data/test_pipe/data_features.json', 'w')
for item in data_list:
    json_data = json.dumps(item)
    dst.write(json_data+"\n")
    count += 1
print("Successfully write out", count)

Successfully write out 20000